version: "3.9"
networks:
  okapia-network:
    driver: bridge
    name: ${DOCKER_NETWORK_NAME}
    
services:
  mysql_wordpress:
    container_name: ${WORDPRESS_MYSQL_CONTAINER_NAME}
    image: mysql:${WORDPRESS_MYSQL_VERSION}
    volumes:
      - $(SITE_FQDN}_db_data:/var/lib/mysql
    networks:
      - okapia-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_MYSQL_DB_PASSW}
      MYSQL_DATABASE: ${WORDPRESS_MYSQL_DB_NAME}
      MYSQL_USER: ${WORDPRESS_MYSQL_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_MYSQL_DB_PASSW}
    
  wordpress:
    container_name: ${WORDPRESS_CONTAINER_NAME}
    depends_on:
      - mysql_wordpress
    image: wordpress:${WORDPRESS_VERSION}
    volumes:
      - $(SITE_FQDN}_wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - okapia-network
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_MYSQL_CONTAINER_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_MYSQL_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_MYSQL_DB_PASSW}
      WORDPRESS_DB_NAME: ${WORDPRESS_MYSQL_DB_NAME}


  webserver:
    depends_on:
      - wordpress
    image: nginx:${WORDPRESS_NGINX_VERSION}
    container_name: ${WORDPRESS_NGINX_CONTAINER_NAME}
    ports:
      - ${SITE_IP_1}:80:80
      - ${SITE_IP_1}:443:443
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    volumes:
      - metricslab_wordpress_data:/var/www/html
      - ${WORDPRESS_NGINX_CONF_D_PATH}
      - ${NGINX_SSL_CERT_PATH}
    networks:
      - okapia-network

volumes:
  $(SITE_FQDN}_db_data: {}
  $(SITE_FQDN}_wordpress_data: {}