version: "3.9"
networks:
  okapia-network:
    driver: bridge
    name: ${DOCKER_NETWORK}
    
services:
  mysql_wordpress:
    container_name: ${WORDPRESS_MYSQL_CONTAINER}
    # image: mysql:${WORDPRESS_MYSQL_VERSION}
    image: jsurf/rpi-mariadb
    volumes:
      - site_db_data:/var/lib/mysql
    networks:
      - okapia-network
    restart: always
    environment:
      TZ: America/New_York
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_MYSQL_DB_PASSW}
      MYSQL_DATABASE: ${WORDPRESS_MYSQL_DB}
      MYSQL_USER: ${WORDPRESS_MYSQL_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_MYSQL_DB_PASSW}
    
  wordpress:
    container_name: ${WORDPRESS_CONTAINER}
    depends_on:
      - mysql_wordpress
    image: wordpress:${WORDPRESS_VERSION}
    volumes:
      - site_wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - okapia-network
    restart: always
    environment:
      TZ: America/New_York
      WORDPRESS_DB_HOST: ${WORDPRESS_MYSQL_CONTAINER}
      WORDPRESS_DB_USER: ${WORDPRESS_MYSQL_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_MYSQL_DB_PASSW}
      WORDPRESS_DB: ${WORDPRESS_MYSQL_DB}
    ports:
      - ${SITE_IP_1}:9000:9000


  webserver:
    depends_on:
      - wordpress
    image: nginx:${WORDPRESS_NGINX_VERSION}
    container_name: ${WORDPRESS_NGINX_CONTAINER}
    environment:
      TZ: America/New_York
      ENV_IP: ${SITE_IP_1}
      WORDPRESS_SERVER: ${WORDPRESS_SERVER}

    
    ports:
      - ${SITE_IP_1}:80:80
      - ${SITE_IP_1}:443:443
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    volumes:
      - site_wordpress_data:/var/www/html
      - ${NGINX_TEMPLATE}
      - ${NGINX_SSL_CERT}
    networks:
      - okapia-network

volumes:
  site_db_data: {}
  site_wordpress_data: {}